name: lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Check with flake8
      run: |
        flake8 